package com.zwl.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ALARM".
 */
@Entity
public class Alarm {

    @Id
    private Long id;
    private Integer hour;
    private Integer minute;
    private Boolean open;

    @Generated
    public Alarm() {
    }

    public Alarm(Long id) {
        this.id = id;
    }

    @Generated
    public Alarm(Long id, Integer hour, Integer minute, Boolean open) {
        this.id = id;
        this.hour = hour;
        this.minute = minute;
        this.open = open;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getHour() {
        return hour;
    }

    public void setHour(Integer hour) {
        this.hour = hour;
    }

    public Integer getMinute() {
        return minute;
    }

    public void setMinute(Integer minute) {
        this.minute = minute;
    }

    public Boolean getOpen() {
        return open;
    }

    public void setOpen(Boolean open) {
        this.open = open;
    }

}
