package com.zwl.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ALARM".
 */
@Entity
public class Alarm {

    @Id
    private Long id;
    private String hour;
    private String minute;
    private Long open;

    @Generated
    public Alarm() {
    }

    public Alarm(Long id) {
        this.id = id;
    }

    @Generated
    public Alarm(Long id, String hour, String minute, Long open) {
        this.id = id;
        this.hour = hour;
        this.minute = minute;
        this.open = open;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHour() {
        return hour;
    }

    public void setHour(String hour) {
        this.hour = hour;
    }

    public String getMinute() {
        return minute;
    }

    public void setMinute(String minute) {
        this.minute = minute;
    }

    public Long getOpen() {
        return open;
    }

    public void setOpen(Long open) {
        this.open = open;
    }

}
