package com.zwl.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zwl.greendao.Word;
import com.zwl.greendao.Alarm;

import com.zwl.greendao.WordDao;
import com.zwl.greendao.AlarmDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wordDaoConfig;
    private final DaoConfig alarmDaoConfig;

    private final WordDao wordDao;
    private final AlarmDao alarmDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wordDaoConfig = daoConfigMap.get(WordDao.class).clone();
        wordDaoConfig.initIdentityScope(type);

        alarmDaoConfig = daoConfigMap.get(AlarmDao.class).clone();
        alarmDaoConfig.initIdentityScope(type);

        wordDao = new WordDao(wordDaoConfig, this);
        alarmDao = new AlarmDao(alarmDaoConfig, this);

        registerDao(Word.class, wordDao);
        registerDao(Alarm.class, alarmDao);
    }
    
    public void clear() {
        wordDaoConfig.clearIdentityScope();
        alarmDaoConfig.clearIdentityScope();
    }

    public WordDao getWordDao() {
        return wordDao;
    }

    public AlarmDao getAlarmDao() {
        return alarmDao;
    }

}
