package com.zwl.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "WORD".
 */
@Entity
public class Word {

    @Id(autoincrement = true)
    private Long id;
    private String hour;
    private String pronunciation;
    private String meaning;
    private Long saveTime;

    @Generated
    public Word() {
    }

    public Word(Long id) {
        this.id = id;
    }

    @Generated
    public Word(Long id, String hour, String pronunciation, String meaning, Long saveTime) {
        this.id = id;
        this.hour = hour;
        this.pronunciation = pronunciation;
        this.meaning = meaning;
        this.saveTime = saveTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHour() {
        return hour;
    }

    public void setHour(String hour) {
        this.hour = hour;
    }

    public String getPronunciation() {
        return pronunciation;
    }

    public void setPronunciation(String pronunciation) {
        this.pronunciation = pronunciation;
    }

    public String getMeaning() {
        return meaning;
    }

    public void setMeaning(String meaning) {
        this.meaning = meaning;
    }

    public Long getSaveTime() {
        return saveTime;
    }

    public void setSaveTime(Long saveTime) {
        this.saveTime = saveTime;
    }

}
