package com.zwl.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WORD".
*/
public class WordDao extends AbstractDao<Word, Long> {

    public static final String TABLENAME = "WORD";

    /**
     * Properties of entity Word.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Hour = new Property(1, String.class, "hour", false, "HOUR");
        public final static Property Pronunciation = new Property(2, String.class, "pronunciation", false, "PRONUNCIATION");
        public final static Property Meaning = new Property(3, String.class, "meaning", false, "MEANING");
        public final static Property SaveTime = new Property(4, Long.class, "saveTime", false, "SAVE_TIME");
    }


    public WordDao(DaoConfig config) {
        super(config);
    }
    
    public WordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WORD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"HOUR\" TEXT," + // 1: hour
                "\"PRONUNCIATION\" TEXT," + // 2: pronunciation
                "\"MEANING\" TEXT," + // 3: meaning
                "\"SAVE_TIME\" INTEGER);"); // 4: saveTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Word entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String hour = entity.getHour();
        if (hour != null) {
            stmt.bindString(2, hour);
        }
 
        String pronunciation = entity.getPronunciation();
        if (pronunciation != null) {
            stmt.bindString(3, pronunciation);
        }
 
        String meaning = entity.getMeaning();
        if (meaning != null) {
            stmt.bindString(4, meaning);
        }
 
        Long saveTime = entity.getSaveTime();
        if (saveTime != null) {
            stmt.bindLong(5, saveTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Word entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String hour = entity.getHour();
        if (hour != null) {
            stmt.bindString(2, hour);
        }
 
        String pronunciation = entity.getPronunciation();
        if (pronunciation != null) {
            stmt.bindString(3, pronunciation);
        }
 
        String meaning = entity.getMeaning();
        if (meaning != null) {
            stmt.bindString(4, meaning);
        }
 
        Long saveTime = entity.getSaveTime();
        if (saveTime != null) {
            stmt.bindLong(5, saveTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Word readEntity(Cursor cursor, int offset) {
        Word entity = new Word( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // hour
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // pronunciation
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // meaning
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // saveTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Word entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setHour(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPronunciation(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMeaning(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSaveTime(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Word entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Word entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Word entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
